# Generated by Django 5.1 on 2024-11-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='instituion',
            new_name='institution',
        ),
    ]
