# Generated by Django 5.1.3 on 2024-12-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_instituion_donation_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cpforcnpj',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
