# Generated by Django 5.1.3 on 2024-12-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_institution_cpforcnpj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='KeyWord',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='institution',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='category',
            new_name='keywords',
        ),
        migrations.DeleteModel(
            name='DonatedBy',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
