# Generated by Django 5.1.3 on 2025-02-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_rename_category_keyword_remove_donation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
